(()=>{
const $=id=>document.getElementById(id);
const SIMPLE=[
 {name:'Cruces secretos',chip:'MISIÓN 1',sub:'Todavía no hay letras. Solo descubre qué hacen las diagonales.',type:'cross',items:[{a:2,b:3,c:1,d:4},{a:3,b:2,c:2,d:5},{a:4,b:1,c:2,d:3}]},
 {name:'Caza la pareja',chip:'MISIÓN 2',sub:'Busca dos números que cumplan dos condiciones al mismo tiempo.',type:'pair',items:[{b:5,c:6,ans:[2,3],opts:[[1,6],[2,3],[-2,-3]]},{b:-5,c:6,ans:[-2,-3],opts:[[2,3],[-1,-6],[-2,-3]]},{b:1,c:-6,ans:[3,-2],opts:[[6,-1],[3,-2],[-3,2]]}]},
 {name:'Construye el patrón',chip:'MISIÓN 3',sub:'Ahora aparecen coeficientes. Prueba qué opción reconstruye exactamente el polinomio.',type:'simple',items:[[2,1,1,3],[3,-2,2,1],[4,3,2,-1]]},
 {name:'Has descubierto el aspa',chip:'MISIÓN 4',sub:'Ese patrón de productos cruzados se llama método del aspa simple.',type:'simple',items:[[3,1,4,-5],[5,2,2,1],[2,-3,3,2]]}
];
const DOUBLE=[
 {name:'Tres cruces, tres resultados',chip:'MISIÓN 1',sub:'El aspa doble repite la misma idea, pero ahora hay tres cruces distintos.',type:'doublecross',items:[{v:[1,4,1,1,1,1],ask:'xy'},{v:[3,1,5,1,-2,2],ask:'y'},{v:[2,3,-1,1,-1,4],ask:'x'}]},
 {name:'Identifica cada aspa',chip:'MISIÓN 2',sub:'Reconoce qué término nace de cada pareja de diagonales.',type:'doublecross',items:[{v:[2,1,-2,1,3,-3],ask:'xy'},{v:[3,4,1,1,2,2],ask:'x'},{v:[2,-1,3,1,2,-2],ask:'y'}]},
 {name:'Factorización guiada',chip:'MISIÓN 3',sub:'Ahora sí: elige los dos trinomios que generan todos los términos.',type:'double',items:[[1,4,1,1,1,1],[3,1,5,1,-2,2],[2,3,-1,1,-1,4]]}
];
let route='simple',stage=0,item=0,stars=0,firstTry=true,status=null;
const first=(n,t='')=>{const a=Math.abs(n),c=t&&a===1?'':a;return`${n<0?'−':''}${c}${t}`};
const later=(n,t='')=>{const a=Math.abs(n),c=t&&a===1?'':a;return`${n<0?'−':'+'} ${c}${t}`};
const sCalc=v=>{const[a,b,c,d]=v;return{x2:a*c,x:a*d+b*c,c:b*d}};
const dCalc=v=>{const[a,b,c,d,e,f]=v;return{x2:a*d,xy:a*e+b*d,y2:b*e,x:a*f+c*d,y:b*f+c*e,c:c*f}};
const sPoly=v=>{const p=sCalc(v);return`${first(p.x2,'x²')} ${later(p.x,'x')} ${later(p.c)}`};
const dPoly=v=>{const p=dCalc(v);return`${first(p.x2,'x²')} ${later(p.xy,'xy')} ${later(p.y2,'y²')} ${later(p.x,'x')} ${later(p.y,'y')} ${later(p.c)}`};
const sFactors=v=>{const[a,b,c,d]=v;return`(${first(a,'x')} ${later(b)})(${first(c,'x')} ${later(d)})`};
const dFactors=v=>{const[a,b,c,d,e,f]=v;return`(${first(a,'x')} ${later(b,'y')} ${later(c)})(${first(d,'x')} ${later(e,'y')} ${later(f)})`};
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
const stages=()=>route==='simple'?SIMPLE:DOUBLE;
function show(id){['startScreen','playScreen','unlockScreen'].forEach(x=>$(x).classList.toggle('hidden',x!==id))}
function hud(){$('stars').textContent=stars;$('routeName').textContent=route==='simple'?'Aspa simple':'Aspa doble';$('routeMini').textContent=route==='simple'?'Aspa simple':'Aspa doble'}
function progress(){let total=0,done=0;stages().forEach((s,i)=>{total+=s.items.length;if(i<stage)done+=s.items.length;else if(i===stage)done+=item});$('progressBar').style.width=`${done/total*100}%`;$('stageCount').textContent=`${done+1} de ${total}`}
function start(){stage=0;item=0;show('playScreen');render()}
function render(){const s=stages()[stage],q=s.items[item];firstTry=true;status=null;$('feedbackWrap').classList.add('hidden');$('stageChip').textContent=s.chip;$('stageTitle').textContent=s.name;$('stageSub').textContent=s.sub;hud();progress();if(s.type==='cross')crossGame(q);else if(s.type==='pair')pairGame(q);else if(s.type==='simple')simpleGame(q);else if(s.type==='doublecross')doubleCrossGame(q);else doubleGame(q)}
function wire(sel,fn){document.querySelectorAll(sel).forEach(b=>b.addEventListener('click',()=>fn(b)))}
function crossVisual(a,b,c,d,label){return`<div class="number-aspa"><svg class="cross-svg" viewBox="0 0 640 270" preserveAspectRatio="none"><line class="cross-line a on" x1="110" y1="72" x2="530" y2="198"></line><line class="cross-line b on" x1="530" y1="72" x2="110" y2="198"></line></svg><div class="node lt">${a}</div><div class="node lb">${b}</div><div class="node rt">${c}</div><div class="node rb">${d}</div><div class="cross-tag">${label}</div></div>`}
function crossGame(q){const target=q.a*q.d+q.c*q.b,opts=shuffle([target,target+2,target-3]);$('gameArea').innerHTML=`<div class="prompt">¿Cuánto suman los dos cruces?</div>${crossVisual(q.a,q.b,q.c,q.d,'cruza y suma')}<div class="answers">${opts.map(v=>`<button class="answer" data-v="${v}" type="button">${v}</button>`).join('')}</div>`;wire('.answer',b=>{const v=+b.dataset.v;if(v===target){b.classList.add('correct');good('¡Lo encontraste!',`${q.a} × ${q.d} = ${q.a*q.d} y ${q.c} × ${q.b} = ${q.c*q.b}. Después se suman.`,` ${q.a*q.d} + ${q.c*q.b} = ${target}`)}else{b.classList.add('wrong');firstTry=false;retry('Mira las diagonales','Primero multiplica cada diagonal. Después suma ambos productos.',`${q.a} × ${q.d} = ${q.a*q.d}<br>${q.c} × ${q.b} = ${q.c*q.b}`)}})}
function pairGame(q){const sb=q.b>=0?`+ ${q.b}`:`− ${Math.abs(q.b)}`,sc=q.c>=0?`+ ${q.c}`:`− ${Math.abs(q.c)}`;$('gameArea').innerHTML=`<div class="prompt">Para <b>x² ${sb}x ${sc}</b>, encuentra la pareja correcta.</div><div class="polynomial">producto = ${q.c} &nbsp; · &nbsp; suma = ${q.b}</div><div class="pair-grid">${shuffle(q.opts).map(p=>`<button class="pair-card" data-a="${p[0]}" data-b="${p[1]}" type="button"><b>${p[0]} &nbsp; y &nbsp; ${p[1]}</b><small>${p[0]} × ${p[1]} = ${p[0]*p[1]} &nbsp; · &nbsp; ${p[0]} + ${p[1]} = ${p[0]+p[1]}</small></button>`).join('')}</div>`;wire('.pair-card',b=>{const p=[+b.dataset.a,+b.dataset.b],ok=(p[0]===q.ans[0]&&p[1]===q.ans[1])||(p[1]===q.ans[0]&&p[0]===q.ans[1]);if(ok){b.classList.add('correct');good('¡Esa pareja sirve!',`Cumple las dos condiciones: producto ${q.c} y suma ${q.b}.`,`(x ${later(p[0])})(x ${later(p[1])})`)}else{b.classList.add('wrong');firstTry=false;retry('Deben cumplirse las dos condiciones','No basta con acertar el producto o la suma por separado.',`Tu pareja: producto ${p[0]*p[1]} · suma ${p[0]+p[1]}<br>Necesitamos: producto ${q.c} · suma ${q.b}`)}})}
function sDistractors(v){const a=v.slice(),b=v.slice();a[1]=-a[1]||1;b[3]+=b[3]>=0?1:-1;return shuffle([v,a,b])}
function simpleGame(v){const target=sCalc(v);$('gameArea').innerHTML=`<div class="prompt">Elige los factores que reconstruyen los tres términos.</div><div class="polynomial">${sPoly(v)}</div><div class="factor-options">${sDistractors(v).map(x=>`<button class="factor-option" data-v="${x.join(',')}" type="button">${sFactors(x)}</button>`).join('')}</div>`;wire('.factor-option',b=>{const x=b.dataset.v.split(',').map(Number),p=sCalc(x),ok=p.x2===target.x2&&p.x===target.x&&p.c===target.c;if(ok){b.classList.add('correct');good(stage===3?'¡Eso es aspa simple!':'¡El patrón encaja!',`Directos: ${x[0]}×${x[2]}=${p.x2} y ${x[1]}×${x[3]}=${p.c}. Cruces: ${x[0]}×${x[3]} + ${x[2]}×${x[1]}=${p.x}.`,'Los directos forman los extremos y la suma cruzada forma el centro.')}else{b.classList.add('wrong');firstTry=false;retry('Revisa el centro','Los extremos pueden coincidir, pero la suma cruzada también debe hacerlo.',`Esta opción produce ${first(p.x2,'x²')} ${later(p.x,'x')} ${later(p.c)}<br>Buscamos ${sPoly(v)}`)}})}
function doubleVisual(v,ask){const[a,b,c,d,e,f]=v,lab=[first(a,'x'),first(b,'y'),c,first(d,'x'),first(e,'y'),f];const onXY=ask==='xy'?'on':'',onY=ask==='y'?'on':'';return`<div class="term-aspa"><svg class="cross-svg" viewBox="0 0 640 270" preserveAspectRatio="none"><line class="cross-line a ${onXY}" x1="110" y1="52" x2="530" y2="135"></line><line class="cross-line a ${onXY}" x1="530" y1="52" x2="110" y2="135"></line><line class="cross-line b ${onY}" x1="110" y1="135" x2="530" y2="218"></line><line class="cross-line b ${onY}" x1="530" y1="135" x2="110" y2="218"></line>${ask==='x'?`<line class="cross-line a on" x1="110" y1="52" x2="530" y2="218"></line><line class="cross-line a on" x1="530" y1="52" x2="110" y2="218"></line>`:''}</svg><div class="node" style="left:9%;top:7%">${lab[0]}</div><div class="node" style="left:9%;top:39%">${lab[1]}</div><div class="node" style="left:9%;bottom:7%">${lab[2]}</div><div class="node" style="right:9%;top:7%">${lab[3]}</div><div class="node" style="right:9%;top:39%">${lab[4]}</div><div class="node" style="right:9%;bottom:7%">${lab[5]}</div><div class="cross-tag">aspa ${ask}</div></div>`}
function doubleCrossGame(q){const p=dCalc(q.v),target=p[q.ask],opts=shuffle([target,target+2,target-2]);$('gameArea').innerHTML=`<div class="prompt">Esta aspa debe producir el coeficiente de <b>${q.ask}</b>. ¿Cuánto da?</div>${doubleVisual(q.v,q.ask)}<div class="answers">${opts.map(v=>`<button class="answer" data-v="${v}" type="button">${v}</button>`).join('')}</div>`;wire('.answer',b=>{const v=+b.dataset.v;if(v===target){b.classList.add('correct');let exp=q.ask==='xy'?`${q.v[0]}×${q.v[4]} + ${q.v[3]}×${q.v[1]}`:q.ask==='y'?`${q.v[1]}×${q.v[5]} + ${q.v[4]}×${q.v[2]}`:`${q.v[0]}×${q.v[5]} + ${q.v[3]}×${q.v[2]}`;good('¡Cruce correcto!',`${exp} = ${target}.`,'Cada aspa tiene una misión distinta: xy, y o x.')}else{b.classList.add('wrong');firstTry=false;retry('Sigue solo las líneas encendidas','Multiplica las dos diagonales destacadas y suma sus resultados.','No necesitas factorizar todavía. Solo descubre qué produce este cruce.')}})}
function dDistractors(v){const a=v.slice(),b=v.slice();a[1]=-a[1]||1;b[5]+=b[5]>=0?1:-1;return shuffle([v,a,b])}
function doubleGame(v){const t=dCalc(v);$('gameArea').innerHTML=`<div class="prompt">Elige la factorización que hace coincidir los tres cruces.</div><div class="polynomial">${dPoly(v)}</div><div class="factor-options">${dDistractors(v).map(x=>`<button class="factor-option" data-v="${x.join(',')}" type="button">${dFactors(x)}</button>`).join('')}</div>`;wire('.factor-option',b=>{const x=b.dataset.v.split(',').map(Number),p=dCalc(x),ok=['x2','xy','y2','x','y','c'].every(k=>p[k]===t[k]);if(ok){b.classList.add('correct');good('¡Aspa doble completa!',`xy=${p.xy}, y=${p.y} y x=${p.x}. Los tres cruces coinciden.`,'Ya no tanteas a ciegas: sabes qué debe comprobar cada aspa.')}else{b.classList.add('wrong');firstTry=false;retry('Comprueba uno por uno','Una sola coincidencia no basta. Deben encajar xy, y y x.',`Esta opción produce xy=${p.xy}, y=${p.y}, x=${p.x}.`)}})}
function sheet(kind,title,text,visual,button){$('feedbackCard').className=`feedback-card ${kind}`;$('feedbackIcon').textContent=kind==='good'?'✓':kind==='try'?'↻':'💡';$('feedbackTitle').textContent=title;$('feedbackText').textContent=text;$('feedbackVisual').innerHTML=visual;$('feedbackBtn').textContent=button;$('feedbackWrap').classList.remove('hidden')}
function good(t,x,v){if(firstTry){stars++;hud();burst()}status='correct';sheet('good',t,x,v,'Continuar →')}
function retry(t,x,v){status='retry';sheet('try',t,x,v,'Volver a intentar')}
function hint(){const s=stages()[stage],q=s.items[item];status='hint';if(s.type==='cross')sheet('info','Pista','Sigue una diagonal cada vez. Multiplica sus extremos y guarda el resultado.',`${q.a} × ${q.d} &nbsp; y &nbsp; ${q.c} × ${q.b}`,'Entendido');else if(s.type==='pair')sheet('info','Pista','Empieza por el producto y descarta parejas que no lo cumplan.',`Necesitas producto ${q.c} y suma ${q.b}.`,'Entendido');else if(s.type==='simple'){const p=sCalc(q);sheet('info','Pista','Comprueba primero los extremos y deja el centro para el final.',`${q[0]}×${q[2]}=${p.x2} &nbsp; · &nbsp; ${q[1]}×${q[3]}=${p.c}`,'Entendido')}else if(s.type==='doublecross')sheet('info','Pista','Solo mira las líneas destacadas. No revises los otros cruces todavía.',`La misión actual es producir ${q.ask}.`,'Entendido');else sheet('info','Pista','Revisa por separado xy, luego y y finalmente x.','Tres comprobaciones pequeñas son más fáciles que una grande.','Entendido')}
function feedbackAction(){if(status==='hint'||status==='retry'){$('feedbackWrap').classList.add('hidden');status=null;return}if(status!=='correct')return;const ss=stages(),s=ss[stage];if(item<s.items.length-1){item++;render()}else if(stage<ss.length-1){stage++;item=0;render()}else finish()}
function finish(){show('unlockScreen');$('unlockTitle').textContent=route==='simple'?'¡Descubriste el método del aspa!':'¡Completaste el aspa doble!';$('unlockText').textContent=route==='simple'?'Primero entendiste los cruces, luego las parejas y recién después factorizar. Ahora la regla ya tiene sentido.':'Ya identificas qué produce cada uno de los tres cruces y cómo verificar una factorización completa.';$('unlockStars').textContent='⭐'.repeat(Math.min(5,Math.max(1,Math.round(stars/2))));$('nextRouteBtn').textContent=route==='simple'?'Aprender aspa doble →':'Volver al inicio'}
function burst(){const colors=['#1677ff','#7566e8','#2e9d62','#d95c8a','#e58a2b'];for(let i=0;i<22;i++){const e=document.createElement('i');e.className='celebrate';e.style.left='50%';e.style.top='45%';e.style.background=colors[i%colors.length];e.style.setProperty('--x',`${(Math.random()-.5)*460}px`);e.style.setProperty('--y',`${(Math.random()-.5)*300}px`);document.body.appendChild(e);setTimeout(()=>e.remove(),850)}}
$('startBtn').addEventListener('click',start);$('hintBtn').addEventListener('click',hint);$('feedbackBtn').addEventListener('click',feedbackAction);$('restartBtn').addEventListener('click',()=>{stars=0;show('startScreen');hud()});$('nextRouteBtn').addEventListener('click',()=>{if(route==='simple'){route='double';document.querySelectorAll('.route-card').forEach(x=>x.classList.toggle('active',x.dataset.route==='double'));start()}else{show('startScreen')}});document.querySelectorAll('.route-card').forEach(b=>b.addEventListener('click',()=>{route=b.dataset.route;document.querySelectorAll('.route-card').forEach(x=>x.classList.toggle('active',x===b));hud()}));hud();show('startScreen');
})();