(()=>{
const $=id=>document.getElementById(id);
const SIMPLE_STAGES=[
 {name:'Cruces secretos',chip:'MISIÓN 1',sub:'Todavía no hay letras. Solo descubre qué hacen las diagonales.',type:'cross',items:[
  {a:2,b:3,c:1,d:4},{a:3,b:2,c:2,d:5},{a:4,b:1,c:2,d:3}
 ]},
 {name:'Caza la pareja',chip:'MISIÓN 2',sub:'Busca dos números que cumplan dos condiciones al mismo tiempo.',type:'pair',items:[
  {b:5,c:6,ans:[2,3],opts:[[1,6],[2,3],[-2,-3]]},
  {b:-5,c:6,ans:[-2,-3],opts:[[2,3],[-1,-6],[-2,-3]]},
  {b:1,c:-6,ans:[3,-2],opts:[[6,-1],[3,-2],[-3,2]]}
 ]},
 {name:'Construye el patrón',chip:'MISIÓN 3',sub:'Ahora aparecen coeficientes. Prueba qué opción reconstruye exactamente el polinomio.',type:'simple',items:[
  [2,1,1,3],[3,-2,2,1],[4,3,2,-1]
 ]},
 {name:'Has descubierto el aspa',chip:'MISIÓN 4',sub:'Ese patrón de productos cruzados se llama método del aspa simple.',type:'simple',items:[
  [3,1,4,-5],[5,2,2,1],[2,-3,3,2]
 ]}
];
const DOUBLE_STAGES=[
 {name:'Tres cruces, tres resultados',chip:'MISIÓN 1',sub:'El aspa doble repite la misma idea, pero ahora hay tres cruces distintos.',type:'doublecross',items:[
  {v:[1,4,1,1,1,1],ask:'xy'},{v:[3,1,5,1,-2,2],ask:'y'},{v:[2,3,-1,1,-1,4],ask:'x'}
 ]},
 {name:'Identifica cada aspa',chip:'MISIÓN 2',sub:'Reconoce qué término nace de cada pareja de diagonales.',type:'doublecross',items:[
  {v:[2,1,-2,1,3,-3],ask:'xy'},{v:[3,4,1,1,2,2],ask:'x'},{v:[2,-1,3,1,2,-2],ask:'y'}
 ]},
 {name:'Factorización guiada',chip:'MISIÓN 3',sub:'Ahora sí: elige los dos trinomios que generan todos los términos.',type:'double',items:[
  [1,4,1,1,1,1],[3,1,5,1,-2,2],[2,3,-1,1,-1,4]
 ]}
];
let route='simple',stage=0,item=0,stars=0,firstTry=true,currentCorrect=null;
const first=(n,t='')=>{const a=Math.abs(n),c=t&&a===1?'':a;return`${n<0?'−':''}${c}${t}`};
const later=(n,t='')=>{const a=Math.abs(n),c=t&&a===1?'':a;return`${n<0?'−':'+'} ${c}${t}`};
const calcSimple=v=>{const[a,b,c,d]=v;return{x2:a*c,x:a*d+b*c,c:b*d}};
const calcDouble=v=>{const[a,b,c,d,e,f]=v;return{x2:a*d,xy:a*e+b*d,y2:b*e,x:a*f+c*d,y:b*f+c*e,c:c*f}};
function polySimple(v){const p=calcSimple(v);return`${first(p.x2,'x²')} ${later(p.x,'x')} ${later(p.c)}`}
function polyDouble(v){const p=calcDouble(v);return`${first(p.x2,'x²')} ${later(p.xy,'xy')} ${later(p.y2,'y²')} ${later(p.x,'x')} ${later(p.y,'y')} ${later(p.c)}`}
function factorSimple(v){const[a,b,c,d]=v;return`(${first(a,'x')} ${later(b)})(${first(c,'x')} ${later(d)})`}
function factorDouble(v){const[a,b,c,d,e,f]=v;return`(${first(a,'x')} ${later(b,'y')} ${later(c)})(${first(d,'x')} ${later(e,'y')} ${later(f)})`}
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function stages(){return route==='simple'?SIMPLE_STAGES:DOUBLE_STAGES}
function updateHud(){$('stars').textContent=stars;$('routeName').textContent=route==='simple'?'Aspa simple':'Aspa doble'}
function show(id){['startScreen','playScreen','unlockScreen'].forEach(x=>$(x).classList.toggle('hidden',x!==id))}
function progress(){const ss=stages();let done=0,total=0;ss.forEach((s,si)=>{total+=s.items.length;if(si<stage)done+=s.items.length;else if(si===stage)done+=item});$('progressBar').style.width=`${Math.round(done/total*100)}%`; $('stageCount').textContent=`${done+1} de ${total}`}
function start(){stage=0;item=0;firstTry=true;show('playScreen');render()}
function render(){const s=stages()[stage],data=s.items[item];firstTry=true;currentCorrect=null;$('stageChip').textContent=s.chip;$('stageTitle').textContent=s.name;$('stageSub').textContent=s.sub;progress();updateHud();$('feedbackWrap').classList.add('hidden');$('hintBtn').classList.remove('hidden');if(s.type==='cross')renderCross(data);if(s.type==='pair')renderPair(data);if(s.type==='simple')renderSimple(data);if(s.type==='doublecross')renderDoubleCross(data);if(s.type==='double')renderDouble(data)}
function crossDiagram(a,b,c,d,tag='?'){return`<div class="number-aspa"><svg class="cross-svg" viewBox="0 0 640 270" preserveAspectRatio="none"><line class="cross-line a on" x1="110" y1="72" x2="530" y2="198"></line><line class="cross-line b on" x1="530" y1="72" x2="110" y2="198"></line></svg><div class="node lt">${a}</div><div class="node lb">${b}</div><div class="node rt">${c}</div><div class="node rb">${d}</div><div class="cross-tag">${tag}</div></div>`}
function answerButtons(opts,handler,formatter=x=>x){return`<div class="answers">${opts.map((x,i)=>`<button class="answer" type="button" data-i="${i}">${formatter(x)}</button>`).join('')}</div>`+`<script></script>`}
function wire(selector,fn){document.querySelectorAll(selector).forEach((b,i)=>b.addEventListener('click',()=>fn(b,i)))}
function renderCross(q){const target=q.a*q.d+q.c*q.b;let opts=shuffle([target,target+2,target-3]);$('gameArea').innerHTML=`<div class="prompt">¿Cuánto suman los dos cruces?</div>${crossDiagram(q.a,q.b,q.c,q.d,'cruza y suma')}<div class="answers">${opts.map(x=>`<button class="answer" type="button" data-v="${x}">${x}</button>`).join('')}</div>`;wire('.answer',(b)=>{const v=+b.dataset.v;if(v===target){b.classList.add('correct');correctFeedback('¡Lo encontraste!',`${q.a} × ${q.d} = ${q.a*q.d} y ${q.c} × ${q.b} = ${q.c*q.b}. Después se suman: ${q.a*q.d} + ${q.c*q.b} = ${target}.`,`Dos diagonales → dos productos → una suma.`)}else{b.classList.add('wrong');firstTry=false;wrongFeedback('Mira las diagonales',`No sumamos los cuatro números. Primero multiplicamos cada diagonal y después sumamos ambos productos.`,`${q.a} × ${q.d} = ${q.a*q.d}<br>${q.c} × ${q.b} = ${q.c*q.b}`)}})}
function renderPair(q){const signB=q.b>=0?`+ ${q.b}`:`− ${Math.abs(q.b)}`,signC=q.c>=0?`+ ${q.c}`:`− ${Math.abs(q.c)}`;$('gameArea').innerHTML=`<div class="prompt">Para <b>x² ${signB}x ${signC}</b>, encuentra la pareja correcta.</div><div class="polynomial">producto = ${q.c} &nbsp; · &nbsp; suma = ${q.b}</div><div class="pair-grid">${shuffle(q.opts).map(p=>`<button class="pair-card" type="button" data-a="${p[0]}" data-b="${p[1]}"><b>${p[0]} &nbsp; y &nbsp; ${p[1]}</b><small>${p[0]} × ${p[1]} = ${p[0]*p[1]} &nbsp; · &nbsp; ${p[0]} + ${p[1]} = ${p[0]+p[1]}</small></button>`).join('')}</div>`;wire('.pair-card',(b)=>{const p=[+b.dataset.a,+b.dataset.b],ok=(p[0]===q.ans[0]&&p[1]===q.ans[1])||(p[1]===q.ans[0]&&p[0]===q.ans[1]);if(ok){b.classList.add('correct');correctFeedback('¡Esa pareja sirve!',`${p[0]} × ${p[1]} = ${q.c} y ${p[0]} + ${p[1]} = ${q.b}. Por eso aparecen los factores (x ${later(p[0])}) y (x ${later(p[1])}).`,`Acabas de usar el corazón del aspa sin memorizar ninguna regla.`)}else{firstTry=false;b.classList.add('wrong');wrongFeedback('Cumple las dos condiciones',`La pareja elegida debe acertar simultáneamente el producto y la suma.`,`Tu pareja: producto ${p[0]*p[1]} · suma ${p[0]+p[1]}<br>Necesitamos: producto ${q.c} · suma ${q.b}`)}})}
function simpleDistractors(v){const a=v.slice(),b=v.slice();a[1]=-a[1]||1;b[3]+=b[3]>=0?1:-1;return shuffle([v,a,b])}
function renderSimple(v){const p=calcSimple(v);$('gameArea').innerHTML=`<div class="prompt">Elige los factores que reconstruyen los tres términos.</div><div class="polynomial">${polySimple(v)}</div><div class="factor-options">${simpleDistractors(v).map((x,i)=>`<button class="factor-option" type="button" data-v="${x.join(',')}">${factorSimple(x)}</button>`).join('')}</div>`;wire('.factor-option',(b)=>{const x=b.dataset.v.split(',').map(Number),q=calcSimple(x),ok=q.x2===p.x2&&q.x===p.x&&q.c===p.c;if(ok){b.classList.add('correct');correctFeedback(stage===3?'¡Eso es aspa simple!':'¡El patrón encaja!',`Directos: ${x[0]}×${x[2]}=${q.x2} y ${x[1]}×${x[3]}=${q.c}. Cruces: ${x[0]}×${x[3]} + ${x[2]}×${x[1]} = ${q.x}.`,`Los productos directos forman los extremos y la suma cruzada forma el término central.`)}else{firstTry=false;b.classList.add('wrong');wrongFeedback('Prueba los cruces',`Los extremos pueden parecer correctos, pero el centro también debe coincidir.`,`Esta opción produce ${first(q.x2,'x²')} ${later(q.x,'x')} ${later(q.c)}<br>Buscamos ${polySimple(v)}`)}})}
function doubleDiagram(v,ask){const[a,b,c,d,e,f]=v;const labels=[first(a,'x'),first(b,'y'),c,first(d,'x'),first(e,'y'),f];const cls=ask==='xy'?'a':ask==='y'?'b':'a';return`<div class="term-aspa"><svg class="cross-svg" viewBox="0 0 640 270" preserveAspectRatio="none"><line class="cross-line a ${ask==='xy'||ask==='x'?'on':''}" x1="110" y1="52" x2="530" y2="135"></line><line class="cross-line a ${ask==='xy'||ask==='x'?'on':''}" x1="530" y1="52" x2="110" y2="135"></line><line class="cross-line b ${ask==='y'?'on':''}" x1="110" y1="135" x2="530" y2="218"></line><line class="cross-line b ${ask==='y'?'on':''}" x1="530" y1="135" x2="110" y2="218"></line>${ask==='x'?`<line class="cross-line a on" x1="110" y1="52" x2="530" y2="218"></line><line class="cross-line a on" x1="530" y1="52" x2="110" y2="218"></line>`:''}</svg><div class="node" style="left:9%;top:7%">${labels[0]}</div><div class="node" style="left:9%;top:39%">${labels[1]}</div><div class="node" style="left:9%;bottom:7%">${labels[2]}</div><div class="node" style="right:9%;top:7%">${labels[3]}</div><div class="node" style="right:9%;top:39%">${labels[4]}</div><div class="node" style="right:9%;bottom:7%">${labels[5]}</div><div class="cross-tag">aspa ${ask}</div></div>`}
function renderDoubleCross(q){const p=calcDouble(q.v),target=p[q.ask],opts=shuffle([target,target+2,target-2]);$('gameArea').innerHTML=`<div class="prompt">Esta aspa debe producir el coeficiente de <b>${q.ask}</b>. ¿Cuánto da?</div>${doubleDiagram(q.v,q.ask)}<div class="answers">${opts.map(x=>`<button class="answer" type="button" data-v="${x}">${x}</button>`).join('')}</div>`;wire('.answer',(b)=>{const val=+b.dataset.v;if(val===target){b.classList.add('correct');const txt=q.ask==='xy'?`${q.v[0]}×${q.v[4]} + ${q.v[3]}×${q.v[1]} = ${target}`:q.ask==='y'?`${q.v[1]}×${q.v[5]} + ${q.v[4]}×${q.v[2]} = ${target}`:`${q.v[0]}×${q.v[5]} + ${q.v[3]}×${q.v[2]} = ${target}`;correctFeedback('¡Cruce correcto!',txt,`En aspa doble cada pareja de diagonales tiene una misión distinta: xy, y o x.`)}else{firstTry=false;b.classList.add('wrong');wrongFeedback('Sigue solo las líneas encendidas',`Multiplica las dos diagonales destacadas y suma sus resultados.`,`No necesitas factorizar todavía; solo entender qué produce este cruce.`)}})}
function doubleDistractors(v){const a=v.slice(),b=v.slice();a[1]=-a[1]||1;b[5]+=b[5]>=0?1:-1;return shuffle([v,a,b])}
function renderDouble(v){const p=calcDouble(v);$('gameArea').innerHTML=`<div class="prompt">Elige la factorización que hace coincidir los tres cruces.</div><div class="polynomial">${polyDouble(v)}</div><div class="factor-options">${doubleDistractors(v).map(x=>`<button class="factor-option" type="button" data-v="${x.join(',')}">${factorDouble(x)}</button>`).join('')}</div>`;wire('.factor-option',(b)=>{const x=b.dataset.v.split(',').map(Number),q=calcDouble(x),ok=['x2','xy','y2','x','y','c'].every(k=>q[k]===p[k]);if(ok){b.classList.add('correct');correctFeedback('¡Aspa doble completa!',`xy = ${q.xy}, y = ${q.y} y x = ${q.x}. Los tres cruces coinciden.`,`Ya no estás tanteando a ciegas: sabes qué debe comprobar cada aspa.`)}else{firstTry=false;b.classList.add('wrong');wrongFeedback('Comprueba uno por uno',`Una sola coincidencia no basta: deben encajar xy, y y x.`,`Esta opción produce xy=${q.xy}, y=${q.y}, x=${q.x}.` )}})}
function feedback(kind,title,text,visual,button){$('feedbackCard').className=`feedback-card ${kind}`;$('feedbackIcon').textContent=kind==='good'?'✓':kind==='try'?'↻':'💡';$('feedbackTitle').textContent=title;$('feedbackText').textContent=text;$('feedbackVisual').innerHTML=visual;$('feedbackBtn').textContent=button;$('feedbackWrap').classList.remove('hidden')}
function correctFeedback(t,x,v){if(firstTry){stars++;updateHud();burst()}currentCorrect=true;feedback('good',t,x,v,'Continuar →')}
function wrongFeedback(t,x,v){currentCorrect=false;feedback('try',t,x,v,'Volver a intentar')}
function hint(){const s=stages()[stage],d=s.items[item];if(s.type==='cross')feedback('info','Pista','Sigue una diagonal cada vez. Multiplica sus extremos y guarda el resultado.',`${d.a} × ${d.d} &nbsp; y &nbsp; ${d.c} × ${d.b}`,'Entendido');else if(s.type==='pair')feedback('info','Pista','Empieza por el producto. Descarta cualquier pareja cuyo producto no sea el término independiente.',`Necesitas producto ${d.c} y suma ${d.b}.`,'Entendido');else if(s.type==='simple'){const p=calcSimple(d);feedback('info','Pista','Comprueba primero los extremos y deja el cruce central para el final.',`Primero: ${d[0]}×${d[2]}=${p.x2} y ${d[1]}×${d[3]}=${p.c}.`,'Entendido')}else if(s.type==='doublecross')feedback('info','Pista','Solo mira las líneas destacadas. No necesitas revisar los otros cruces todavía.',`La misión actual es producir ${d.ask}.`,'Entendido');else feedback('info','Pista','Revisa los cruces por separado: xy, luego y y finalmente x.','Tres comprobaciones pequeñas son más fáciles que una grande.','Entendido')}
function next(){if(currentCorrect===false){$('feedbackWrap').classList.add('hidden');return}if(currentCorrect===null){$('feedbackWrap').classList.add('hidden');return}const ss=stages(),s=ss[stage];if(item<s.items.length-1){item++;render();return}if(stage<ss.length-1){stage++;item=0;render();return}finish()}
function finish(){show('unlockScreen');$('unlockTitle').textContent=route==='simple'?'¡Descubriste el método del aspa!':'¡Completaste el aspa doble!';$('unlockText').textContent=route==='simple'?'Primero entendiste los cruces, luego las parejas y recién después factorizar. Ahora la regla ya tiene sentido.':'Ya identificas qué produce cada uno de los tres cruces y cómo verificar una factorización completa.';$('unlockStars').textContent='⭐'.repeat(Math.min(5,Math.max(1,Math.round(stars/2))));$('nextRouteBtn').textContent=route==='simple'?'Aprender aspa doble →':'Volver al inicio';}
function burst(){const colors=['#1677ff','#7566e8','#2e9d62','#d95c8a','#e58a2b'];for(let i=0;i<24;i++){const e=document.createElement('i');e.className='celebrate';e.style.left='50%';e.style.top='45%';e.style.background=colors[i%colors.length];e.style.setProperty('--x',`${(Math.random()-.5)*480}px`);e.style.setProperty('--y',`${(Math.random()-.5)*320}px`);document.body.appendChild(e);setTimeout(()=>e.remove(),850)}}
$('startBtn').addEventListener('click',start);$('hintBtn').addEventListener('click',hint);$('feedbackBtn').addEventListener('click',next);$('restartBtn').addEventListener('click',()=>{stars=0;show('startScreen');updateHud()});$('nextRouteBtn').addEventListener('click',()=>{if(route==='simple'){route='double';document.querySelectorAll('.route-card').forEach(x=>x.classList.toggle('active',x.dataset.route==='double'));stage=0;item=0;start()}else{show('startScreen')}});document.querySelectorAll('.route-card').forEach(b=>b.addEventListener('click',()=>{route=b.dataset.route;document.querySelectorAll('.route-card').forEach(x=>x.classList.toggle('active',x===b));updateHud()}));updateHud();show('startScreen');
})();