(()=>{
const $=id=>document.getElementById(id);
const SIMPLE=[[1,2,1,3],[2,1,1,3],[3,-2,2,1],[3,1,4,-5],[4,3,2,-1],[2,-3,3,2],[5,1,2,-3],[3,4,2,1],[4,-1,3,2],[2,5,5,-1]];
const DOUBLE=[[1,4,1,1,1,1],[3,1,5,1,-2,2],[2,3,-1,1,-1,4],[2,1,-2,1,3,-3],[3,4,1,1,2,2],[2,-1,3,1,2,-2],[1,2,-1,2,1,3],[3,-2,1,1,1,-2],[2,3,2,2,-1,1],[1,-3,2,3,2,-1]];
let mode='simple',round=1,score=0,combo=0,best=0,hearts=3,correct=0,current=[],timeLeft=12,maxTime=12,timer=null,running=false,sound=true,answered=false;
const first=(n,t='')=>{const a=Math.abs(n),c=t&&a===1?'':a;return`${n<0?'−':''}${c}${t}`};
const later=(n,t='')=>{const a=Math.abs(n),c=t&&a===1?'':a;return`${n<0?'−':'+'} ${c}${t}`};
const shuffle=a=>{a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function calc(v){if(mode==='simple'){const[a,b,c,d]=v;return{x2:a*c,x:a*d+b*c,c:b*d}}const[a,b,c,d,e,f]=v;return{x2:a*d,xy:a*e+b*d,y2:b*e,x:a*f+c*d,y:b*f+c*e,c:c*f}}
function poly(v){const p=calc(v);if(mode==='simple')return`${first(p.x2,'x²')} ${later(p.x,'x')} ${later(p.c)}`;return`${first(p.x2,'x²')} ${later(p.xy,'xy')} ${later(p.y2,'y²')} ${later(p.x,'x')} ${later(p.y,'y')} ${later(p.c)}`}
function factors(v){if(mode==='simple'){const[a,b,c,d]=v;return`(${first(a,'x')} ${later(b)})(${first(c,'x')} ${later(d)})`}const[a,b,c,d,e,f]=v;return`(${first(a,'x')} ${later(b,'y')} ${later(c)})(${first(d,'x')} ${later(e,'y')} ${later(f)})`}
function equivalent(a,b){if(a.length!==b.length)return false;if(a.every((v,i)=>v===b[i]))return true;if(mode==='simple')return a.every((v,i)=>v===[b[2],b[3],b[0],b[1]][i]);return a.every((v,i)=>v===[b[3],b[4],b[5],b[0],b[1],b[2]][i])}
function beep(freq=660,dur=.08){if(!sound)return;try{const C=window.AudioContext||window.webkitAudioContext;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.07,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+dur);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+dur);o.onended=()=>c.close()}catch(e){}}
function updateHud(){$('score').textContent=score;$('combo').textContent=`x${Math.max(1,combo)}`;$('hearts').textContent='♥ '.repeat(hearts).trim()+' ♡ '.repeat(3-hearts).trim();$('round').textContent=round}
function show(screen){['startScreen','playScreen','gameOver'].forEach(id=>$(id).classList.toggle('hidden',id!==screen))}
function makeDistractor(base,seed){const d=base.slice();const i=(seed*2+round)%d.length;if(seed===0)d[i]=-d[i]||1;else if(seed===1)d[i]+=d[i]>=0?1:-1;else{const j=(i+1)%d.length;[d[i],d[j]]=[d[j],d[i]]}if(equivalent(d,base))d[d.length-1]+=(d[d.length-1]>=0?2:-2);return d}
function renderOptions(){let opts=[{v:current,ok:true}];for(let s=0;s<4&&opts.length<3;s++){const d=makeDistractor(current,s);if(!opts.some(o=>factors(o.v)===factors(d)))opts.push({v:d,ok:false})}opts=shuffle(opts);$('options').innerHTML=opts.map((o,i)=>`<button class="answer-card" type="button" data-ok="${o.ok}" data-index="${i}">${factors(o.v)}</button>`).join('');$('options').querySelectorAll('.answer-card').forEach(b=>b.addEventListener('click',()=>choose(b)))}
function choose(btn){if(!running||answered||btn.classList.contains('dim'))return;if(btn.dataset.ok==='true'){answered=true;running=false;clearInterval(timer);btn.classList.add('correct');const gain=Math.max(50,Math.round(timeLeft*10*(1+combo*.2)));combo++;best=Math.max(best,combo);correct++;score+=gain;updateHud();$('toast').className='toast good';$('toast').textContent=`+${gain} · ¡Correcto!`;beep(820,.1);burst();$('options').querySelectorAll('.answer-card').forEach(b=>{if(b!==btn)b.classList.add('dim')});setTimeout(()=>revealAspa(current),280)}else{btn.classList.add('wrong');btn.disabled=true;hearts--;combo=0;updateHud();$('toast').className='toast bad';$('toast').textContent='Fallaste una vida. Aún puedes acertar.';beep(190,.13);if(hearts<=0){running=false;clearInterval(timer);setTimeout(endGame,550)}}}
function startRound(){answered=false;running=true;$('laserStage').classList.add('hidden');$('laserSvg').innerHTML='';$('laserMessage').textContent='';$('toast').className='toast';$('toast').textContent='';const bank=mode==='simple'?SIMPLE:DOUBLE;current=bank[(round-1)%bank.length].slice();maxTime=mode==='simple'?12:18;timeLeft=maxTime;$('seconds').textContent=maxTime;$('timerBar').style.width='100%';$('polynomial').textContent=poly(current);renderOptions();updateHud();clearInterval(timer);const started=performance.now();timer=setInterval(()=>{const elapsed=(performance.now()-started)/1000;timeLeft=Math.max(0,maxTime-elapsed);$('seconds').textContent=Math.ceil(timeLeft);$('timerBar').style.width=`${timeLeft/maxTime*100}%`;if(timeLeft<=0){clearInterval(timer);running=false;hearts--;combo=0;updateHud();$('toast').className='toast bad';$('toast').textContent='⏱ Tiempo. Pierdes una vida.';beep(160,.16);if(hearts<=0)setTimeout(endGame,500);else setTimeout(nextRound,850)}},100)}
function svgNode(x,y,text){return`<circle class="laser-node" cx="${x}" cy="${y}" r="43"></circle><text class="laser-text" x="${x}" y="${y}">${text}</text>`}
function line(id,cls,x1,y1,x2,y2){return`<line id="${id}" class="laser-line ${cls}" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"></line>`}
function revealAspa(v){$('options').classList.add('hidden');$('laserStage').classList.remove('hidden');const svg=$('laserSvg'),p=calc(v);if(mode==='simple'){const[a,b,c,d]=v;svg.innerHTML=line('l1','line-purple',230,82,670,218)+line('l2','line-purple',670,82,230,218)+svgNode(230,82,first(a,'x'))+svgNode(230,218,b)+svgNode(670,82,first(c,'x'))+svgNode(670,218,d);$('laserMessage').textContent=`${a}×${d} + ${c}×${b} = ${p.x}  →  ${p.x}x`}else{const[a,b,c,d,e,f]=v;svg.innerHTML=line('l1','line-purple',230,48,670,150)+line('l2','line-purple',670,48,230,150)+line('l3','line-orange',230,150,670,252)+line('l4','line-orange',670,150,230,252)+line('l5','line-green',230,48,670,252)+line('l6','line-green',670,48,230,252)+svgNode(230,48,first(a,'x'))+svgNode(230,150,first(b,'y'))+svgNode(230,252,c)+svgNode(670,48,first(d,'x'))+svgNode(670,150,first(e,'y'))+svgNode(670,252,f);$('laserMessage').textContent=`xy: ${p.xy}   ·   y: ${p.y}   ·   x: ${p.x}`}animateLasers()}
async function animateLasers(){const groups=mode==='simple'?[['l1','l2']]:[['l1','l2'],['l3','l4'],['l5','l6']];for(const g of groups){g.forEach(id=>$(id)?.classList.add('flash'));await wait(mode==='simple'?850:480);g.forEach(id=>$(id)?.classList.remove('flash'));await wait(90)}await wait(220);nextRound()}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function nextRound(){$('options').classList.remove('hidden');if(hearts<=0)return endGame();if(round>=10)return endGame();round++;startRound()}
function startGame(){round=1;score=0;combo=0;best=0;hearts=3;correct=0;show('playScreen');startRound()}
function endGame(){clearInterval(timer);running=false;$('finalScore').textContent=score;$('finalCorrect').textContent=correct;$('bestCombo').textContent=`x${Math.max(1,best)}`;$('finalTitle').textContent=correct>=8?'¡Dominio total!':correct>=5?'¡Buen ritmo!':'Sigue entrenando';show('gameOver')}
function hint(){if(!running||answered)return;const wrong=[...$('options').querySelectorAll('.answer-card')].filter(b=>b.dataset.ok==='false'&&!b.disabled&&!b.classList.contains('dim'));if(wrong.length){wrong[Math.floor(Math.random()*wrong.length)].classList.add('dim');score=Math.max(0,score-25);updateHud();$('toast').className='toast';$('toast').textContent='50/50 activado · −25 puntos';beep(430,.06)}}
function skip(){if(!running||answered)return;clearInterval(timer);running=false;combo=0;$('toast').className='toast';$('toast').textContent='Reto saltado';setTimeout(nextRound,250)}
function burst(){const colors=['#1778f2','#7a65e8','#39a96b','#e75e91','#f59a45'];for(let i=0;i<28;i++){const s=document.createElement('i');s.className='burst';s.style.left='50%';s.style.top='45%';s.style.background=colors[i%colors.length];s.style.setProperty('--x',`${(Math.random()-.5)*520}px`);s.style.setProperty('--y',`${(Math.random()-.5)*360}px`);document.body.appendChild(s);setTimeout(()=>s.remove(),800)}}
$('playBtn').addEventListener('click',startGame);$('againBtn').addEventListener('click',startGame);$('changeModeBtn').addEventListener('click',()=>show('startScreen'));$('hintBtn').addEventListener('click',hint);$('skipBtn').addEventListener('click',skip);$('soundBtn').addEventListener('click',()=>{sound=!sound;$('soundBtn').textContent=sound?'🔊':'🔇'});document.querySelectorAll('.mode-card').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.mode-card').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode}));updateHud();show('startScreen');
})();